### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by appel268576** [FundedByMe/django-paypal-adaptive#1]
Hi there.

I am trying to use this library you built for adaptive payments and have found a few missing libraries - but cannot find the last one which is the MoneyField.

from money.contrib.django.models.fields import MoneyField

Do you mind pointing out where you found this?

Regards

**Comment by jmelett** [comment]
pip install -e git+git://github.com/poswald/python-money.git#egg=python-money

Cheers

**Comment by antonagestam** [comment]
Fixed in https://github.com/FundedByMe/django-paypal-adaptive/commit/e748042f760f806eec08f97a27b35968fe0647c9#setup.py
